### ISSUE TITLE
As a developer i want to remove magic numbers from the code to improve maintainability, flexibility and ease scalability

### ISSUE THREAD

**Issue by August-Brandt** [ITU-BDSA23-GROUP10/Chirp#110]
The code currently contains magic numbers like `limit` in `UserTimeline.cshtml.cs`, `Public.cshtml.cs`, and `PaginationVievComponent.cs` is set to 32 in 3 different files. This should be made more maintainable by having some way of getting the `limit` from one place.

Acceptance: 
- The code doesn't refer to magic numbers
- Common numbers are not set in multiple files

**Comment by Alex-itu** [comment]
We added a field in to the PageData class, which have the limit to how many cheeps is view on each page
