### ISSUE TITLE
As a developer, i'd like to add tests for testing Chirp! CLI app for errors

### ISSUE THREAD

**Issue by JonasSkjodt** [ITU-BDSA23-GROUP10/Chirp#14]
2.a continued.

Add unit tests to your Chirp! CLI app.
Add unit tests for suitable functionality. For example, conversion of UNIX timestamps to user readable times and similar functionality are good candidates for unit testing.

**Comment by Slug-Boi** [comment]
Currently only runs tests on the published exe file instead of running on the csproj og dll files. This needs to be fixed

**Comment by JonasSkjodt** [comment]
This issue includes making tests to end to end tests.
