### ISSUE TITLE
As a user, I'd like to know that a user does not exist when accessing an invalid usertimeline

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#166]
**Acceptance criteria**

1. When attempting to access an invalid user's timeline, such that `User.Identity is null || !User.Identity.IsAuthenticated` ...
- [x] Replace displayed title `<InvalidUser>'s Timeline` and paragraph `There are no cheeps so far.` with title a) `This user does not exist.` or b) `User <InvalidUser> does not exist.` If possible, in a red box to indicate an invalid user-action.
- [x] Replace pagination with a `Return to homepage` button or text with either c) href attribute or d) redirect-method to `<webpage>/`

**Comment by Slug-Boi** [comment]
Working on this on branch InvalidUserErrorPage
