### ISSUE TITLE
As a dev, I'd like to refactor tests to encapsulate the new user repository's methods.

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#180]
**Acceptance criteria**
- [ ] Assert that **GetUserById** can retrieve an existing user-object via their id.
- [ ] Assert that **GetUserByName** can retrieve an existing user-object via their name.
- [ ] Assert that **GetUserByName** can retrieve an existing user-object , who's got an email, via their email.
- [ ] Assert that **InsertUser** can insert and save a new user-object in the DbSetUser. Check that they exist. 
- [ ] Assert that **DeleteUser** can delete an existing user-object . Check that they do not exist.
- [ ] Assert that **CreateUser** can create and insert a new user-object in the DbSetUser. Check that the user exists.
- [ ] Assert that **FollowUser** inserts a user's id as FollowerId and another user's id as FolowingId.

**Comment by Slug-Boi** [comment]
@Haruyzal can we get an update on how this issue is going?

**Comment by Haruyzal** [comment]
@Slug-Boi I'm not assigned to this task, so no updates from me. @August-Brandt, if you're too busy with tickets (and life), I can also take over this ticket?
