### ISSUE TITLE
As a dev, I'd like to turn FollowingId and FollowerId into ForeignKeys to ensure database integrity.

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#184]

**Comment by Alex-itu** [comment]
Made a foreign relation between follows and user. But still not sure if it's done. People are welcome to look at it, in branch: foreignkeyOnthefollowtable

Will finish tomorrow

**Comment by Alex-itu** [comment]
This is not need for the work it requires, so changing it back to table that only have ids
