### ISSUE TITLE
As a developer, I want to use an external library to process CSV-files, for easier CSV-regex handling

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#2]
From desc: 2.a

Why:
- Libraries have pre-tested functionalities
- Prevents future messy code and hours of debugging

Acceptance Criteria:
- CsvHelper or comparable library is implemented
- Chirp users can write and read "Goodbye, World!"

**Comment by August-Brandt** [comment]
It done
