### ISSUE TITLE
As a dev, I'd like a ViewComponent for common elements shared between Public- and UserTimeline, to increase codebase maintainability.

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#215]
Dependent upon #229 being pushed to avoid merge issues and double work.

**Acceptance criterias**
---
Code within .cshtml.cs
- [x] Create a ViewComponent-file, i.e. `TimelineViewComponent.cs`
- [x] Identify common code shared between `Public.cshtml.cs` and `UserTimeline.cshtml.cs`
- [x] Extract said commonality and merge them together into `TimelineViewComponent`
- [x] Ensure said merge checks  whether the user is within **public timeline** or **my timeline**, ensuring correct display of element

Code within .cshtml
- [x] Within Pages/Components, create a folder, i.e. `Timeline`
- [x] Within said folder, create a file titled `default.cshtml`
- [x] In `Public.cshtml` and `UserTimeline.cshtml`, find their commonalities
- [x] Extract said commonality and merge them together into `Timeline/default.cshtml`
- [x] Ensure said merge checks and therefor correctly displays elements depending on whether the user is within **public timeline** or **my timeline**

**Comment by JonasSkjodt** [comment]
Actively being coded on the branch ReduceHTMLRedundancy.

Currently both public and timeline has a common component, both cs and html files. The Hashtag pages shares a bit of commonality with former pages as well, I'll integrate it later this weekend.
