### ISSUE TITLE
As a user, I'd like to be taken into a register-formular for Chirp, now that there's a register-text besides login, for enhanced user-experience of non-GitHub users.

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#234]
When not logged in, the navigation bar displays: `public timeline | register login`.

a) If we only allow GitHub authentication logins, we shouldn't even have a register "button".
b) If we will allow non-GitHub authentication logins, we should actually create a registerpage, form and method.

**Acceptance criteria**
---
**If a) is agreed upon and chosen.**
- [ ] Remove the text `register` to remove registration-expectations for the user.

**If b) is agreed upon and chosen.**
- [ ] Separate displayed text `register login`, for example by having `register | login`
- [ ] Create a register razorpage with boxes, e.g. `Username: [ chirpy ]`, `E-mail: [ example@example.com ]`, `Password: [ ex4mple*]`, and a button e.g. `Register` or `Sign up` that, when pressed, will validate availability and regex for username, email and password, wherefter `InsertUser()` is called upon
- [ ] Ensure `InsertUser()` (in UserRepo) can take a string password argument as an optional parameter, and that it properly inserts password into the user object.
- [ ] In folder and namespace Chirp.Infrastructure.Models, ensure that model User has an optional password field with getter-setter.
- [ ] Ensure that the inserted user password gets hashed before being inserted into the Database
- [ ] Ensure in a test that we can retrieve the correct password from the Database, and that it is unhashed upon final retrieval.
- [ ] Ensure that in `<website>/profile`, that a user can only change their passwords if they didn't log in via GitHub Auth.

**Comment by Haruyzal** [comment]
@Slug-Boi should we at least address our current Register text and remove it in that case? :)

**Comment by Slug-Boi** [comment]
I was wrong reopened to remove register
