### ISSUE TITLE
Cheep-msg starting with @ cannot be written/stored in db

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#35]
The stored msg will contain an empty string.

ReadCheeps() is not a problem: It is possible to manually insert a string starting with @ in the csv-file and have the string returned properly.

Acceptance:
* Be able to store the string: "@", using _dotnet run cheep_ in the CSV-file.

**Comment by Slug-Boi** [comment]
This seems like a really weird bug with how CSVHelper saves to a file. Using Raw string literals didn't even fix this issue so I'm going to close this issue since we now just have an error message that displays so users cant post cheeps like that
