### ISSUE TITLE
2.d) As a group I would like to utilize proper pair programming using the methods in the slides from lecture 5

### ISSUE THREAD

**Issue by Slug-Boi** [ITU-BDSA23-GROUP10/Chirp#53]
Acceptance:
- Smaller group based pair programming (commits should now be co-authored by 2-3 people most of time)
- Using the driver & navigator approach (this should be reflected by the commit co-authoring as mentioned above) 
- Switching more often (Every 15-20 minutes ideally) this should be visable with slightly more varied code as people write differently

**Comment by Haruyzal** [comment]
I'm unsure how Helge/Rasmus/TAs would be able to check these criterias. Would we be able to find more measureable acceptance criterias? c:

**Comment by Slug-Boi** [comment]
> I'm unsure how Helge/Rasmus/TAs would be able to check these criterias. Would we be able to find more measureable acceptance criterias? c:

I've tried to make it more measurable sadly this is mostly something the group just has to measure as it's only really visable outside on the commits being co-authored by less people. If we do a logbook we could also document who was doing pair programming in there 🤷🏻‍♂️
