### ISSUE TITLE
2.B) As a group member, I like to continue to release and deploy automatically to Azure App Service

### ISSUE THREAD

**Issue by Alex-itu** [ITU-BDSA23-GROUP10/Chirp#72]
Continue to release and deploy automatically. That is, during the next weeks you bring multiple new versions Chirp.Razor running into production, i.e., to deploy them automatically to Azure App Service. The latest version of the application in production is always the latest version of the application in your main branch. You decide if it is the latest tagged version or the latest committed version, i.e., if your workflow is triggered by pushes to main or pushes of tags.

Likely, you have a respective GitHub Actions workflow already from last week. If not, this task is here to signal that it is high time creating a working deployment workflow.

---- acceptante ----
- Azure automatically deployment

**Comment by Haruyzal** [comment]
We shall remember to release, thank you for the reminder Helge :D
