### ISSUE TITLE
1.b) As a dev, I'd like to extend my repositories for more functionalities

### ISSUE THREAD

**Issue by Haruyzal** [ITU-BDSA23-GROUP10/Chirp#88]
Note: CheepViewModel and CheepDTO might be used interchangeably as we wish to rename to CheepDTO.

**Acceptance criteria**

- [x]  A method that returns the obj. ```Author``` when passed arg. ```<Name>``` matches ```Author.Name```.

- [x] A method that returns the obj. ```Author``` when passed arg. ```<Email>``` matches ```Author.Email```.

- [x] A void method that creates a new instance of obj. ```Author```.

- [ ] A method that returns cheeps from a specific page:
- The method must return list of ```CheepDTO``` by retrieving a ```Cheep```-obj and parse its author's name, message and timestamp (as strings) to a new ```CheepDTO``` that is returned.

- [ ] A method that returns cheeps from a specific page, where the cheeps are written by a specific author.
- The method has an (optional) parameter of string authorName must find an ```Author```-objt and return the author's list of ```CheepDTO``` by retrieving a ```Cheep```-obj and parse its author's name, message and timestamp (as strings) to a new ```CheepDTO``` that is returned.

- [ ] A void method that creates a new instance of obj. ```Cheep```.
- If the author does not exist, create the author.

**Comment by Slug-Boi** [comment]
Is the method that returns cheeps from a certain page the same as GetSome()? Since it technically returns the cheeps from a certain page using offset and limit? =o same for the author one. Or do we need a specific method which takes a page number in and then uses that method to return the cheeps?

**Comment by Slug-Boi** [comment]
Work on this issue is taking place on the Extended Repositories branch

**Comment by Haruyzal** [comment]
@Slug-Boi The task does not specify which values to use/parse in the method you mentioned, so yes, we can check off that task because of GetSome() :D

**Comment by Slug-Boi** [comment]
Thats great I think we may have to do that change on main or another branch since the DTO rename change happened on another branch
