### ISSUE TITLE
1.d) As a developer i want the project to adhere to Command Query Seperation

### ISSUE THREAD

**Issue by August-Brandt** [ITU-BDSA23-GROUP10/Chirp#89]
[1.d](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_07/README_PROJECT.md#1d-command-query-separation)
Exposed methods in the repositories should folow the CQS. 

Acceptance:
- Exposed commands in the repositories **only** change the state of the database
- Exposed quries in the repositories **only** retreive data from the database

**Comment by JonasSkjodt** [comment]
Just to expand on this with more wording,[ the queries return a result and _do not change the observable state of the system_ (are free of side effects)](https://martinfowler.com/bliki/CommandQuerySeparation.html).

So our code should still adhere to CQS in the _CreateAuthor()_ method (where we get in a set) in AuthorRepository.cs.

We could visit this at a later date, depending on our workload.

**Comment by Alex-itu** [comment]
It could maybe possible to let the database handle this issue and simple catch the error thrown be it. That way it would be possible to issue a insect command and then not worry about checking for exisisting duplicates. Given that the insect is in a table with a primary key or unique.
