### ISSUE TITLE
As a developer i want the program to create a database file in temp also if the environment variable points to a non-existing file

### ISSUE THREAD

**Issue by August-Brandt** [ITU-BDSA23-GROUP10/Chirp#93]
Currently the program only creates the database file in temp if the environment vaiable is empty. The program should also create the database file in the temp folder if the file pointed to by the env variable does not exists.

Acceptence:
- When the program is run with an environment variable that points to a path that does not exist then the database file is created in the temp folder.

**Comment by Slug-Boi** [comment]
If i remember correctly the database file should be created in the location that the env variable is pointing to if it's a valid path (with the folders) which is currently should be doing. But it could just be me misreading what the issue is referring to :)

**Comment by August-Brandt** [comment]
Currently the program program puts the database in the temp folder if the env. variable is null. But if the is env. variable is not set to a valid path that causes problems.

**Comment by August-Brandt** [comment]
Since the project is changing to SQL server instead of SQLite. The connection string will no longer be to a file and therefore this issue no longer applies
